# Ejercicios Parte II
## Li Yang, Patiy - 20191294
Los ejercicios 5, 6, 7, 8 y 9 de esta parte deben leer su data de links en Github y el código y los resultados deben ser publicados en páginas en Github. Este es un proyecto distinto y los ejercicios tienen que ser publicados en una página diferente.

## Ejercicio 5

1. Get a polygons map of the lowest administrative unit possible.    
2. Get a table of variables for those units. At least 3 numerical variables.
3. Preprocess both tables and get them ready for merging. 
4. Do the merging, making the changes needed so that you keep the most columns.

**5.1. Subdivisiones administrativas a nivel de prefecturas en China (ADM2)**

Fuente: [China - Subnational Administrative Boundaries](https://data.humdata.org/dataset/cod-ab-chn).

Notar que ADM1 es la subdivisión a nivel de provincia, mientras que ADM2, es aquella a nivel de prefectura. El GeoDataFrame del mapa de polígonos de las subdiviciones administrativas ADM2 fue procesado anteriormente en el Jupyter Notebook PreproEvaluación#4_2da-Parte_Mining_GeoDFs. Este se encuentra proyectado con un crs de 3415.

In [52]:
import geopandas as gpd

China3415_maps = "https://github.com/Ciencia-de-datos-espaciales-2023-2/Evaluacion4_2da-Parte_Mining_GeoDFs/raw/main/maps/China3415_maps/China3415_GeoMap.gpkg"
China_ADM2 = gpd.read_file(China3415_maps,layer="PrefectureLevel_ADM2")
China_ADM2.head()

ADM1_PCODE ADM2_PCODE                                          ADM1+ADM2  \
0      CN065   CN065100              XinjiangUygurAutonomousRegion+Karamay   
1      CN065   CN065060  XinjiangUygurAutonomousRegion+ChangjiHuiAutono...   
2      CN065   CN065130              XinjiangUygurAutonomousRegion+Shihezi   
3      CN015   CN015120       InnerMongoliaAutonomousRegion+XilingolLeague   
4      CN021   CN021020                             LiaoningProvince+Benxi   

                                            geometry  
0  POLYGON ((-1970139.776 3501254.481, -1968482.7...  
1  POLYGON ((-1435866.505 3385323.591, -1441284.2...  
2  POLYGON ((-1920371.401 3365547.617, -1922878.1...  
3  POLYGON ((993809.799 3455055.691, 1001127.812 ...  
4  POLYGON ((1534098.705 2791209.973, 1528098.355...

**5.2.,5.3. y 5.4. Preprocesamiento de tablas con variables numéricas y *Merging***

No se logró conseguir una tabla con 3 variables numéricas, pero sí 3 tablas con 1 variable numérica cada una. Por tanto, se deberá realizar un *merge* de las 3 tablas. Las variables numéricas son las siguientes:

- Índice normalizado de diferencia de vegetación ( "normalized difference vegetation index" o NDVI). Fuente: [China: NDVI at Subnational Level](https://data.humdata.org/dataset/chn-ndvi-subnational)

- Indicadores SDG 7.1.1 ("Sustainable Development Goals") del porcentaje de la población con acceso a la electricidad. Fuente: [SDG Indicator 7.1.1: Access to Electricity, 2023 Release (2020 – 2022)](https://sedac.ciesin.columbia.edu/data/set/sdgi-7-1-1-access-electricity-2023)

- Indicadores SDG 9.1.1 ("Sustainable Development Goals") del índice de acceso rural, que alude al porcentaje de la población que vive al menos a 2 kilómetros de una carretera transitable. Fuente: [SDG Indicator 9.1.1: The Rural Access Index (RAI), 2023 Release (2015 – 2022)](https://sedac.ciesin.columbia.edu/data/set/sdgi-9-1-1-rai-2023)

Las tres tablas ya fueron procesadas de forma individual en el Jupyter Notebook PreproEvaluación#4_2da-Parte_Mining_GeoDFs:

`a) Tabla con los valores promedios de índices normalizados de la diferencia de vegetación (NDVI, por sus siglas en inglés) en subdivisiones administrativas a nivel de prefecturas (AMD2) en China: NDVI_China2023`

Nota: La tabla contiene 334 datos

In [53]:
import pandas as pd

NDVI_Link = "https://github.com/Ciencia-de-datos-espaciales-2023-2/Evaluacion4_2da-Parte_Mining_GeoDFs/raw/main/data/NDVI_China2023_prepro.csv"
NDVI_China2023 = pd.read_csv(NDVI_Link,index_col=0)
NDVI_China2023.head()

ADM2_PCODE  NDVI_avg
0   CN053160    0.6006
1   CN053020    0.6633
2   CN053060    0.6767
3   CN054050    0.3202
4   CN053130    0.6666

`b) Tabla con indicadores del porcentaje de la población con acceso a la electricidad en subdivisiones administrativas a nivel de prefecturas (AMD2) en China: SDG711_ElectricityAccess_China2023`

Nota: La tabla contiene 344 datos

In [54]:
SDG711_Link = "https://github.com/Ciencia-de-datos-espaciales-2023-2/Evaluacion4_2da-Parte_Mining_GeoDFs/raw/main/data/SDG711_ElectricityAccess_China2023_prepro.csv"
SDG711_ElectricityAccess_China2023 = pd.read_csv(SDG711_Link,index_col=0)
SDG711_ElectricityAccess_China2023.head()

SDG711_pct      ADM1+ADM2
0   51.056611   Anhui+Anqing
1   70.505872   Anhui+Bengbu
2   57.124918   Anhui+Bozhou
3   65.594567   Anhui+Chaohu
4   50.803892  Anhui+Chizhou

`c) Tabla con indicadores porcentuales del índice de acceso rural en subdivisiones administrativas a nivel de prefecturas (AMD2) en China: SDG911_RuralAccess_China2023`

Nota: La tabla contiene 344 datos

In [55]:
SDG911_Link = "https://github.com/Ciencia-de-datos-espaciales-2023-2/Evaluacion4_2da-Parte_Mining_GeoDFs/raw/main/data/SDG911_RuralAccess_China2023_prepro.csv"
SDG911_RuralAccess_China2023 = pd.read_csv(SDG911_Link,index_col=0)
SDG911_RuralAccess_China2023.head()

SDG911_pct      ADM1+ADM2
0   84.749728   Anhui+Anqing
1   94.908604   Anhui+Bengbu
2   95.735585   Anhui+Bozhou
3   95.028170   Anhui+Chaohu
4   80.718768  Anhui+Chizhou

Como se observa, no es posible realizar un *merge* de las tres columnas, porque no todas comparten una en común. Por esto, se realizará lo siguiente:
1. *Merge* de SDG711_ElectricityAccess_China2023 y SDG911_RuralAccess_China2023, mediante la columna "ADM1+ADM2".
2. *Merge* de NDVI_China2023 y SDG911_RuralAccess_China2023, mediante la columna "ADM2_PCODE".
3. *Fuzy Merge* de las tablas resultantes de 1 y 2, porque comparten la columna "ADM1+ADM2", pero el formato de los nombres no es el mismo.

`d) *Merging* de SDG711_ElectricityAccess_China2023 y SDG911_RuralAccess_China2023 mediante la columna "ADM1+AM2"`

Nota: Ambas tablas contienen 344 filas y comparten las mismas filas correspondientes a subdivisiones ADM2. La tabla resultante del *merging* también contiene 344 filas, lo cual evidencia que no se ha repetido u omitido algún dato.

In [56]:
a = set(SDG711_ElectricityAccess_China2023["ADM1+ADM2"].to_list()) 
b = set(SDG911_RuralAccess_China2023["ADM1+ADM2"].to_list())
a-b, b-a

(set(), set())

In [57]:
ElectricityRuralAccess_China2023 = SDG711_ElectricityAccess_China2023.merge(
    SDG911_RuralAccess_China2023, on = "ADM1+ADM2")

ElectricityRuralAccess_China2023

SDG711_pct          ADM1+ADM2  SDG911_pct
0     51.056611       Anhui+Anqing   84.749728
1     70.505872       Anhui+Bengbu   94.908604
2     57.124918       Anhui+Bozhou   95.735585
3     65.594567       Anhui+Chaohu   95.028170
4     50.803892      Anhui+Chizhou   80.718768
..          ...                ...         ...
339   79.097747    Zhejiang+Quzhou   99.601174
340   94.671754  Zhejiang+Shaoxing   96.554436
341   95.714004   Zhejiang+Taizhou   94.300258
342   97.430320   Zhejiang+Wenzhou   92.875470
343   98.749609  Zhejiang+Zhoushan   93.638234

[344 rows x 3 columns]

`e) Merging de NDVI_China2023 y China_ADM2 mediante la columna "ADM2_PCODE"`

Nota: NDVI_China2023 contiene 334 filas, mientras que China_ADM2, 361. Por tanto, hay 27 valores de "ADM2_PCODE" en China_ADM2 que no se encuentran en NDVI_China2023. Así, la tabla resultante del merging también contiene 334 filas.

In [58]:
a = set(NDVI_China2023 ["ADM2_PCODE"].to_list()) 
b = set( China_ADM2["ADM2_PCODE"].to_list())
len(b-a)

27

In [59]:
ADM2_NDVI_China2023= China_ADM2.merge(NDVI_China2023, on = "ADM2_PCODE" )
ADM2_NDVI_China2023

ADM1_PCODE ADM2_PCODE                                          ADM1+ADM2  \
0        CN065   CN065100              XinjiangUygurAutonomousRegion+Karamay   
1        CN065   CN065060  XinjiangUygurAutonomousRegion+ChangjiHuiAutono...   
2        CN065   CN065130              XinjiangUygurAutonomousRegion+Shihezi   
3        CN015   CN015120       InnerMongoliaAutonomousRegion+XilingolLeague   
4        CN021   CN021020                             LiaoningProvince+Benxi   
..         ...        ...                                                ...   
329      CN034   CN034120                            AnhuiProvince+Ma'anshan   
330      CN034   CN034150                                 AnhuiProvince+Wuhu   
331      CN046   CN046050                             HainanProvince+Danzhou   
332      CN046   CN046080                              HainanProvince+Haikou   
333      CN046   CN046150                               HainanProvince+Sanya   

                                              geometry  NDVI_avg  
0    POLYGON ((-1970139.776 3501254.481, -1968482.7...    0.1105  
1    POLYGON ((-1435866.505 3385323.591, -1441284.2...    0.1252  
2    POLYGON ((-1920371.401 3365547.617, -1922878.1...    0.1602  
3    POLYGON ((993809.799 3455055.691, 1001127.812 ...    0.1543  
4    POLYGON ((1534098.705 2791209.973, 1528098.355...    0.3589  
..                                                 ...       ...  
329  POLYGON ((953768.864 1653335.953, 949470.407 1...    0.3478  
330  POLYGON ((879714.068 1672197.689, 883803.058 1...    0.4377  
331  MULTIPOLYGON (((-30157.327 341902.121, -30159....    0.7388  
332  MULTIPOLYGON (((141006.867 392722.649, 141006....    0.5759  
333  MULTIPOLYGON (((15070.411 199741.112, 15069.53...    0.7342  

[334 rows x 5 columns]

`f) Fuzzy Merging de NDVI_China2023 y ElectricityRuralAccess_China2023 mediante la columna "ADM1+ADM2"`

Nota: Se realizó un *fuzzy merge*, porque los valores en la columna "ADM1+ADM2" no coinciden exactamente en ambas tablas. En total, se realizaron cuatro fuzzy merging para conservar el mayor número de filas posible.

Antes de realizar el fuzzy merge, se determinó el número de valores de "ADM1+ADM2" que no coinciden en ambas tablas. Con esto, se obtuvo que ningún valor coincidía, pues la resta del conjunto de valores de "ADM1+ADM2" en ElectricityRuralAccess_China2023 con los de NDVI_China2023 dio 344 resultados, equivalente al número total de filas en ElectricityRuralAccess_China2023. Del mismo modo, la resta de conjuntos de NDVI_China2023 con los de ElectricityRuralAccess_China2023 dio 334 resultados, equivalente al número total de filas en NDVI_China2023.

In [60]:
ADM2_NDVI_set = set(ADM2_NDVI_China2023["ADM1+ADM2"].to_list())
ElectricityRuralAccess_set = set(ElectricityRuralAccess_China2023["ADM1+ADM2"].to_list())

restaER_AN = ElectricityRuralAccess_set - ADM2_NDVI_set
restaAN_ER = ADM2_NDVI_set - ElectricityRuralAccess_set

#len(restaER_AN)
len(restaER_AN), len(restaAN_ER)

(344, 334)

**f.1) Primer *Fuzzy Merging***

In [61]:
from thefuzz import process as fz

FuzzChanges1 = {x:fz.extractOne(x,restaER_AN)[0] for x in sorted(restaAN_ER) 
                if fz.extractOne(x,restaER_AN)[1]==86}

# Errores encontrados que deben corregirse manualmente y sustraerse del diccionario FuzzChanges1  
ManualChanges_toDiscard1= {'HainanProvince+Danzhou': 'Hainan+Hainan',
                   'HainanProvince+Haikou':'Hainan+Hainan',
                   'HainanProvince+Sanya':'Hainan+Hainan',
                   'JilinProvince+Baicheng':'Jilin+Jilin',
                   'JilinProvince+Baishan':'Jilin+Baishan',
                   'JilinProvince+Changchun':'Jilin+Jilin',
                   'JilinProvince+Liaoyuan':'Jilin+Jilin',
                   'JilinProvince+Siping':'Jilin+Jilin',
                   'JilinProvince+YanbianKoreanAutonomousPrefecture': 'Jilin+Jilin',
                   'QinghaiProvince+HainanTibetanAutonomousPrefecture': 'Hainan+Hainan',
                   "ShaanxiProvince+Xi'an":"Sichuan+Ya'an",
                   'ShaanxiProvince+Yulin':'Guangxi+Yulin',
                   "ShandongProvince+Tai'an":"Sichuan+Ya'an",
                   "SichuanProvince+Guang'an":"Sichuan+Ya'an"}

TotalChanges1 = dict(set(FuzzChanges1.items())-set(ManualChanges_toDiscard1.items()))

ADM2_NDVI_China2023["ADM1+ADM2"].replace(to_replace=TotalChanges1,inplace=True)

Aún hay 108 valores en la columna "ADM1+ADM2" en ADM2_NDVI_China2023 que no coinciden con los de ElectricityRuralAccess:

In [63]:
ADM2_NDVI_set = set(ADM2_NDVI_China2023["ADM1+ADM2"].to_list())
ElectricityRuralAccess_set = set(ElectricityRuralAccess_China2023["ADM1+ADM2"].to_list())

restaER_AN_2 = ElectricityRuralAccess_set - ADM2_NDVI_set
restaAN_ER_2 = ADM2_NDVI_set - ElectricityRuralAccess_set

len(restaER_AN_2), len(restaAN_ER_2)

(128, 108)

**f.2) Segundo *Fuzzy Merging***

Se realiza un segundo *Fuzzy Merging* para intentar recuperar el mayor número de filas restantes.

In [64]:
FuzzChanges2 = {x:fz.extractOne(x,restaER_AN_2)[0] for x in sorted(restaAN_ER_2) 
                if fz.extractOne(x,restaER_AN_2)[1]>=80}

# Errores encontrados que deben corregirse manualmente y sustraerse del diccionario FuzzChanges1  
ManualChanges_toDiscard2= {'HainanProvince+Danzhou': 'Hainan+Hainan',
                           'HainanProvince+Haikou': 'Hainan+Hainan',
                           'HainanProvince+Sanya': 'Hainan+Hainan',
                           'QinghaiProvince+HainanTibetanAutonomousPrefecture': 'Hainan+Hainan',
                           'QinghaiProvince+HainanTibetanAutonomousPrefecture': 'Hainan+Hainan',
                           "ShaanxiProvince+Xi'an":"Jiangxi+Ji'an",
                           "SichuanProvince+Guang'an":"Shandong+Tai'an",
                           'XinjiangUygurAutonomousRegion+AltayPrefecture':'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+BayingolinMongoliaAutonomousPrefecture':'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+BortalaMongolAutonomousPrefecture': 'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+ChangjiHuiAutonomousPrefecture':'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+HotanPrefecture': 'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+IliKazakAutonomousPrefecture':'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+KashiPrefecture': 'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+KizilsuKirgizAutonomousPrefecture': 'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+TarbaĝatayPrefecture': 'XinjiangUygur+Aksu',
                           'XinjiangUygurAutonomousRegion+Turpan': 'XinjiangUygur+Aksu'}
        
TotalChanges2 = dict(set(FuzzChanges2.items())-set(ManualChanges_toDiscard2.items()))
ADM2_NDVI_China2023["ADM1+ADM2"].replace(to_replace=TotalChanges2,inplace=True)

El número de valores en la columna "ADM1+ADM2" en ADM2_NDVI_China2023 que no coinciden con los de ElectricityRuralAccess ha reducido de 108 a 53 con el segundo *fuzzy merging*:

In [65]:
ADM2_NDVI_set = set(ADM2_NDVI_China2023["ADM1+ADM2"].to_list())
ElectricityRuralAccess_set = set(ElectricityRuralAccess_China2023["ADM1+ADM2"].to_list())

restaER_AN_3 = ElectricityRuralAccess_set - ADM2_NDVI_set
restaAN_ER_3 = ADM2_NDVI_set - ElectricityRuralAccess_set

len(restaER_AN_3), len(restaAN_ER_3)

(75, 53)

**f.3) Tercer *Fuzzy Merging***

Se realiza un tercer *Fuzzy Merging* para intentar recuperar el mayor número de filas restantes.

In [66]:
FuzzChanges3 = {x:fz.extractOne(x,restaER_AN_3)[0] for x in sorted(restaAN_ER_3) 
                if fz.extractOne(x,restaER_AN_3)[1]>=50}

# Errores encontrados que deben corregirse manualmente y sustraerse del diccionario FuzzChanges1  
ManualChanges_toDiscard3= {'HainanProvince+Danzhou': 'Hainan+Hainan',
                           'HainanProvince+Haikou':'Hainan+Hainan',
                           'HainanProvince+Sanya': 'Hainan+Hainan',
                           'HubeiProvince+Xiangyang': 'Hubei+Xiangfan',
                           'InnerMongoliaAutonomousRegion+HingganLeague':'NeiMongol+Alxa',
                           'InnerMongoliaAutonomousRegion+Ulanqab':'NeiMongol+Alxa',
                           'LiaoningProvince+Yingkou':'Xizang+Ngari',
                           'QinghaiProvince+HainanTibetanAutonomousPrefecture':'Hainan+Hainan',
                           'QinghaiProvince+YushuTibetanAutonomousPrefecture': 'Hubei+Xiantao',
                           "ShaanxiProvince+Xi'an": "Shaanxi+Yan'an",
                           "SichuanProvince+Guang'an": "Shaanxi+Yan'an",
                           'SichuanProvince+LiangshanYiAutonomousPrefecture': 'Shanxi+Luliang',
                           'TibetAutonomousRegion+Lhoka': 'NeiMongol+Alxa',
                           'TibetAutonomousRegion+Xigazê': "NeiMongol+Xing'an",
                           'XinjiangUygurAutonomousRegion+BayingolinMongoliaAutonomousPrefecture': 'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+BortalaMongolAutonomousPrefecture': 'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+ChangjiHuiAutonomousPrefecture': 'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+HotanPrefecture': 'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+IliKazakAutonomousPrefecture': 'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+KashiPrefecture': 'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+KizilsuKirgizAutonomousPrefecture':'XinjiangUygur+Altay',
                           'XinjiangUygurAutonomousRegion+TarbaĝatayPrefecture':'XinjiangUygur+Altay'}
                                                      
TotalChanges3 = dict(set(FuzzChanges3.items())-set(ManualChanges_toDiscard3.items()))
ADM2_NDVI_China2023["ADM1+ADM2"].replace(to_replace=TotalChanges3,inplace=True)

El número de valores en la columna "ADM1+ADM2" en ADM2_NDVI_China2023 que no coinciden con los de ElectricityRuralAccess ha reducido de 53 a 21 con el tercer fuzzy merging:

In [68]:
ADM2_NDVI_set = set(ADM2_NDVI_China2023["ADM1+ADM2"].to_list())
ElectricityRuralAccess_set = set(ElectricityRuralAccess_China2023["ADM1+ADM2"].to_list())

restaER_AN_4 = ElectricityRuralAccess_set - ADM2_NDVI_set
restaAN_ER_4 = ADM2_NDVI_set - ElectricityRuralAccess_set

len(restaER_AN_4), len(restaAN_ER_4)

(43, 21)

**f.4) Cuarto *Fuzzy Merging***

Se realiza un último *Fuzzy Merging* para intentar recuperar el mayor número de columnas de las restantes.

In [71]:
FuzzChanges4 = {x:fz.extractOne(x,restaER_AN_4) for x in sorted(restaAN_ER_4) 
                if fz.extractOne(x,restaER_AN_4)[1]>=50}

Del cuarto *Fuzzy Merging* realizado, solo se observan dos nombres equivalentes. Por tanto, del total de 334 filas, se han logrado recuperar 334-21+2 = 315.

In [72]:
TotalChanges4 = {'SichuanProvince+LiangshanYiAutonomousPrefecture': 'Sichuan+LiangshanYi',
                'InnerMongoliaAutonomousRegion+Ulanqab':'NeiMongol+UlaanChab'}

ADM2_NDVI_China2023["ADM1+ADM2"].replace(to_replace=TotalChanges4,inplace=True)

In [73]:
ADM2_NDVI_set = set(ADM2_NDVI_China2023["ADM1+ADM2"].to_list())
ElectricityRuralAccess_set = set(ElectricityRuralAccess_China2023["ADM1+ADM2"].to_list())

restaER_AN_5 = ElectricityRuralAccess_set - ADM2_NDVI_set
restaAN_ER_5 = ADM2_NDVI_set - ElectricityRuralAccess_set

len(restaER_AN_5), len(restaAN_ER_5)

(41, 19)

`g) Fuzzy Merging de ADM2_NDVI_China2023 y ElectricityRuralAccess_China2023 mediante la columna "ADM1+ADM2"`

Finalmente, tras asegurar que se ha logrado recuperar el mayor número de filas posible (315), se realiza el *merge* entre ambas tablas.

In [77]:
ADM2_NDVI_ER_China2023= ADM2_NDVI_China2023.merge(ElectricityRuralAccess_China2023, on = "ADM1+ADM2")
ADM2_NDVI_ER_China2023

ADM1_PCODE ADM2_PCODE                ADM1+ADM2  \
0        CN065   CN065100    XinjiangUygur+Karamay   
1        CN065   CN065130    XinjiangUygur+Shihezi   
2        CN015   CN015120       NeiMongol+XilinGol   
3        CN021   CN021020           Liaoning+Benxi   
4        CN062   CN062040          Gansu+Jiayuguan   
..         ...        ...                      ...   
310      CN022   CN022090      Jilin+YanbianKorean   
311      CN023   CN023080  Heilongjiang+Mudanjiang   
312      CN021   CN021040          Liaoning+Dalian   
313      CN062   CN062100          Gansu+Pingliang   
314      CN034   CN034150               Anhui+Wuhu   

                                              geometry  NDVI_avg  SDG711_pct  \
0    POLYGON ((-1970139.776 3501254.481, -1968482.7...    0.1105   93.430917   
1    POLYGON ((-1920371.401 3365547.617, -1922878.1...    0.1602   90.450636   
2    POLYGON ((993809.799 3455055.691, 1001127.812 ...    0.1543   47.628330   
3    POLYGON ((1534098.705 2791209.973, 1528098.355...    0.3589   83.573906   
4    POLYGON ((-916257.824 2656685.604, -915093.765...    0.0780   98.106990   
..                                                 ...       ...         ...   
310  MULTIPOLYGON (((1966883.942 3009006.671, 19666...    0.3903   77.620545   
311  POLYGON ((1854708.756 3429274.247, 1856117.027...    0.3489   67.108739   
312  MULTIPOLYGON (((1161673.363 2517466.154, 11616...    0.3056   87.393022   
313  POLYGON ((-178141.426 2162423.939, -177070.322...    0.3662   47.468925   
314  POLYGON ((879714.068 1672197.689, 883803.058 1...    0.4377   88.761587   

     SDG911_pct  
0     96.716076  
1     99.387351  
2     60.672959  
3     87.998619  
4     96.070047  
..          ...  
310   84.603794  
311   76.832415  
312   98.659882  
313   90.866637  
314   97.805658  

[315 rows x 7 columns]

## Ejercicio 6

1. Choose a numeric variable from your merged data.
2. Decide which is the  best classification scheme for that variable. #Histograma para la variable numérica
3. Make a map for the best scheme. #Ejm: mapa de Perú para IDH
4. Make a histogram for the best scheme. #Con el mejor algoritmo

## Ejercicio 7

Compute the neighbors of the capital of your country. Plot the results for each of the options.

## Ejercicio 8

1. Compute the Moran's coefficient for **all** your numeric variables.
    
2. Make a scatter plot for each variable.

## Ejercicio 9
    
1. Compute the Local Moran for the variables in your data that have significant spatial correlation. 
2. Create a new column for each of those variables, with a label ('0 no_sig', '1 hotSpot', '2 coldOutlier', '3 coldSpot', '4 hotOutlier').
3. Prepare a map for each of the variables analyzed, showing the spots and outliers. (3 variables: 3 mapas)